# This workflow will build a Java project with Maven
# For more information see httpshelp.github.comactionslanguage-and-framework-guidesbuilding-and-testing-java-with-maven

name Java CI with Maven

on
  push
    branches [ main ]
  pull_request
    branches [ main ]

jobs
  build

    runs-on ubuntu-latest

    steps
    - uses actionscheckout@v2
    - name Set up JDK 1.8
      uses actionssetup-java@v1
      with
        java-version 1.8
    - name Build with Maven
      run mvn -B package --file pom.xml